### ISSUE TITLE
Wrong Appium server version installed

### ISSUE THREAD

**Issue by JordanLongstaff** [AppiumTestDistribution/appium-installer#13]
The latest version of Appium is 2.4.1, but `appium-installer` installed version 2.0.1.

I think you need to update the release of `appium-installer`. The code appears to correctly install the latest version, but that change was committed months after the version number in `package.json` was updated.

**Comment by saikrishna321** [comment]
@JordanLongstaff Please check v3.0.0

**Comment by JordanLongstaff** [comment]
Fixed. Thanks!
