### ISSUE TITLE
(bug): binaries are not available after setup

### ISSUE THREAD

**Issue by christian-bromann** [AppiumTestDistribution/appium-installer#5]
When running `npx appium-installer` I manage to set up an Android environment. However if I then try to launch an emulator, it fails because the binary is apparently not available. See following screenshot:

![Screenshot 2023-05-01 at 23 27 13](https://user-images.githubusercontent.com/731337/235594700-932e2b03-226b-49d9-b330-12ce313dca83.png)

Can you help me understand what is going on here?

**Comment by saikrishna321** [comment]
@christian-bromann I think emulator is not set in PATH. Let me check whats happening. 

I have this

```
export ANDROID_HOME=/Users/saikrishna/Library/Android/sdk
export PATH=$PATH:$ANDROID_HOME/emulator
```

**Comment by christian-bromann** [comment]
Gotcha, is there a way to document or run this as part of the process? Is there a way to extend `PATH` as part of the `.env` file?

**Comment by saikrishna321** [comment]
`run this as part of the process` I'm looking into this.

**Comment by saikrishna321** [comment]
@christian-bromann I checked the code we are already taking the ANDROID_HOME https://github.com/AppiumTestDistribution/appium-installer/blob/main/src/android.js#L14-L20

Did you run the Boot emulator before running the Android setup step ?

**Comment by saikrishna321** [comment]
@christian-bromann Can you try version `2.1.0` and let me know.
